CREATE DATABASE WarehouseDB
GO

USE WarehouseDB

CREATE TABLE Items
(
	Id INT NOT NULL CONSTRAINT PK_Items_Id PRIMARY KEY IDENTITY,
	[Name] VARCHAR(100) NOT NULL
)

CREATE TABLE Stock
(
	Id INT NOT NULL CONSTRAINT PK_Stock_Id PRIMARY KEY IDENTITY,
	IdItem INT NOT NULL CONSTRAINT FK_Stock_IdItem FOREIGN KEY REFERENCES Items(Id),
	[Count] INT NOT NULL CONSTRAINT CH_Stock_Count CHECK ([Count] > 0)
)

CREATE TABLE Suppliers
(
	Id INT NOT NULL CONSTRAINT PK_Suppliers_Id PRIMARY KEY IDENTITY,
	[Name] VARCHAR(100) NOT NULL
)

CREATE TABLE Staff
(
	Id INT NOT NULL CONSTRAINT PK_Staff_Id PRIMARY KEY IDENTITY,
	[Name] VARCHAR(100) NOT NULL
)

CREATE TABLE Clients
(
	Id INT NOT NULL CONSTRAINT PK_Clients_Id PRIMARY KEY IDENTITY,
	[Name] VARCHAR(100) NOT NULL
)

CREATE TABLE Receiption
(
	Id INT NOT NULL CONSTRAINT PK_Receiption_Id PRIMARY KEY IDENTITY,
	IdSupplier INT NOT NULL CONSTRAINT FK_Receiption_IdSupplier FOREIGN KEY REFERENCES Suppliers(Id),
	IdItem INT NOT NULL CONSTRAINT FK_Receiption_IdItem FOREIGN KEY REFERENCES Items(Id),
	IdPerformer INT NOT NULL CONSTRAINT FK_Receiption_IdPerformer FOREIGN KEY REFERENCES Staff(Id),
	[Count] INT NOT NULL CONSTRAINT CH_Receiption_Count CHECK ([Count] > 0)
)

CREATE TABLE Expenditures
(
	Id INT NOT NULL CONSTRAINT PK_Expenditures_Id PRIMARY KEY IDENTITY,
	IdClient INT NOT NULL CONSTRAINT FK_Expenditures_IdClient FOREIGN KEY REFERENCES Clients(Id),
	IdItem INT NOT NULL CONSTRAINT FK_Expenditures_IdItem FOREIGN KEY REFERENCES Items(Id),
	IdPerformer INT NOT NULL CONSTRAINT FK_Expenditures_IdPerformer FOREIGN KEY REFERENCES Staff(Id),
	[Count] INT NOT NULL CONSTRAINT CH_Expenditures_Count CHECK ([Count] > 0)
)


USE master
DROP DATABASE WarehouseDB
GO